# Basic Python

## 1. Split this string

In [ ]:
s = "Hi there Sam!"

In [1]:
s = "Hi there Sam!"
x = s.split()
print(x)

['Hi', 'there', 'Sam!']


## 2. Use .format() to print the following string. 

### Output should be: The diameter of Earth is 12742 kilometers.

In [ ]:
planet = "Earth"
diameter = 12742

In [3]:
planet = "Earth"
diameter = 12742
print('The diameter of {} is {} Kilometers.'.format(planet,diameter));

The diameter of Earth is 12742 Kilometers.


## 3. In this nest dictionary grab the word "hello"

In [ ]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}

In [4]:
d = {'k1':[1,2,3,{'tricky':['oh','man','inception',{'target':[1,2,3,'hello']}]}]}
print(d['k1'][3]["tricky"][3]["target"][3])

hello


# Numpy

In [5]:
import numpy as np

## 4.1 Create an array of 10 zeros? 
## 4.2 Create an array of 10 fives?

In [6]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [8]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

## 5. Create an array of all the even integers from 20 to 35

In [12]:
print(np.arange(20,35,2))

[20 22 24 26 28 30 32 34]


## 6. Create a 3x3 matrix with values ranging from 0 to 8

In [22]:
np.arange(0,9).reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 7. Concatinate a and b 
## a = np.array([1, 2, 3]), b = np.array([4, 5, 6])

In [24]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
np.concatenate ((a,b),axis=0)

array([1, 2, 3, 4, 5, 6])

# Pandas

## 8. Create a dataframe with 3 rows and 2 columns

In [25]:
import pandas as pd


In [26]:
A=np.random.randint(10,size=(3,2))
df=pd.DataFrame(A)
df

0  1
0  5  7
1  4  7
2  0  0

## 9. Generate the series of dates from 1st Jan, 2023 to 10th Feb, 2023

In [35]:
Dinesh=pd.date_range(start = '01-01-2023', end = '02-10-2023',freq ='6H')
for val in Dinesh:
  print(val)

2023-01-01 00:00:00
2023-01-01 06:00:00
2023-01-01 12:00:00
2023-01-01 18:00:00
2023-01-02 00:00:00
2023-01-02 06:00:00
2023-01-02 12:00:00
2023-01-02 18:00:00
2023-01-03 00:00:00
2023-01-03 06:00:00
2023-01-03 12:00:00
2023-01-03 18:00:00
2023-01-04 00:00:00
2023-01-04 06:00:00
2023-01-04 12:00:00
2023-01-04 18:00:00
2023-01-05 00:00:00
2023-01-05 06:00:00
2023-01-05 12:00:00
2023-01-05 18:00:00
2023-01-06 00:00:00
2023-01-06 06:00:00
2023-01-06 12:00:00
2023-01-06 18:00:00
2023-01-07 00:00:00
2023-01-07 06:00:00
2023-01-07 12:00:00
2023-01-07 18:00:00
2023-01-08 00:00:00
2023-01-08 06:00:00
2023-01-08 12:00:00
2023-01-08 18:00:00
2023-01-09 00:00:00
2023-01-09 06:00:00
2023-01-09 12:00:00
2023-01-09 18:00:00
2023-01-10 00:00:00
2023-01-10 06:00:00
2023-01-10 12:00:00
2023-01-10 18:00:00
2023-01-11 00:00:00
2023-01-11 06:00:00
2023-01-11 12:00:00
2023-01-11 18:00:00
2023-01-12 00:00:00
2023-01-12 06:00:00
2023-01-12 12:00:00
2023-01-12 18:00:00
2023-01-13 00:00:00
2023-01-13 06:00:00


## 10. Create 2D list to DataFrame

lists = [[1, 'aaa', 22],
         [2, 'bbb', 25],
         [3, 'ccc', 24]]

In [ ]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]

In [39]:
lists = [[1, 'aaa', 22], [2, 'bbb', 25], [3, 'ccc', 24]]
df = pd.DataFrame (lists, columns = ['Tag','Letters','Numbers'])
print(df)

   Tag Letters  Numbers
0    1     aaa       22
1    2     bbb       25
2    3     ccc       24
